#############################################################################
# Generated by PAGE version 4.5
# in conjunction with Tcl version 8.6
#    May 08, 2015 11:38:33 PM


set vTcl(actual_gui_bg) wheat
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) wheat
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top38
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top38 {base} {
    if {$base == ""} {
        set base .top38
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background wheat 
    wm focusmodel $top passive
    wm geometry $top 1914x522+0+24
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    listbox $top.lis39 \
        -background white -font TkFixedFont -foreground {#000000} 
    .top38.lis39 configure -font TkFixedFont
    vTcl:DefineAlias "$top.lis39" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    listbox $top.lis40 \
        -background white -font TkFixedFont -foreground {#000000} 
    .top38.lis40 configure -font TkFixedFont
    vTcl:DefineAlias "$top.lis40" "Listbox2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but41 \
        -activebackground {#f4bcb2} -background wheat -command <<<< \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text <<<< 
    vTcl:DefineAlias "$top.but41" "Button1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lis39 \
        -in $top -x 10 -y 40 -anchor nw -bordermode ignore 
    place $top.lis40 \
        -in $top -x 250 -y 40 -anchor nw -bordermode ignore 
    place $top.but41 \
        -in $top -x 170 -y 100 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top38

